# Generated by Django 4.1.2 on 2022-11-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='', max_length=250)),
                ('admin_pas', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('price', models.CharField(default='', max_length=250)),
                ('quantity', models.CharField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
                ('usertype', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
