# Generated by Django 4.1.2 on 2022-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='status',
            field=models.CharField(default='', max_length=250),
        ),
    ]
